#ifndef SIMULATORUTILS_GLOBAL_H
#define SIMULATORUTILS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SIMULATORUTILS_LIBRARY)
#  define SIMULATORUTILS_EXPORT Q_DECL_EXPORT
#else
#  define SIMULATORUTILS_EXPORT Q_DECL_IMPORT
#endif

#endif // SIMULATORUTILS_GLOBAL_H
